### ISSUE TITLE
Double comptage electricité recharge véhicules électriques ? 

### ISSUE THREAD

**Issue by lgodron** [datagir/nosgestesclimat#1473]
## Poser une question 

Bonjour,
Il me semble que le simulateur compte à la fois les émissions liées aux distances parcourues par les véhicules électriques (incluant l'électricité consommée) et les émissions liées à mes factures d'électricité, qui incluent l'électricité pour recharger mon véhicule. Est-ce exact ? 

## Proposer une amélioration 

Si mon doute est avéré, permettre dans le test de signaler  quel % de la recharge se fait à domicile en moyenne. 
Si mon doute est injustifié, ajouter un item de FAQ :)

(https://github.com/datagir/nosgestesclimat/blob/master/CONTRIBUTING.md)*

N'hésitez pas à inclure des chiffres, des sources, des articles de presse, une ébauche de calcul par vos soins etc.

**Comment by Clemog** [comment]
Bonjour, effectivement, très bonne remarque, nous avons identifié le problème ici : https://github.com/datagir/nosgestesclimat/issues/646
J'ajoute votre proposition à l'issue ! Merci !

**Comment by mquandalle** [comment]
Ce ticket n'étant par résolu il me semble qui pourrait être réouvert.

Une fois #2338 intégré, qui introduit une variable intermédiaire sur la consommation en kwh du véhicule électrique, il est possible de resoudre ce problème de double comptage en ajoutant une question type : 

```yaml
question: Dans quelle proportion rechargez-vous votre véhicule électrique à domicile ?
applicable si: transport . voiture . véhicule électrique
par défaut: 80%
```

Et l'utiliser pour retrancher de l'impact du logement la part de la facture d'électricité qui correspond à la recharge du véhicule.
