### ISSUE TITLE
Réflexion sur la traduction et l'i18n [WIP]

### ISSUE THREAD

**Issue by laem** [datagir/nosgestesclimat#1519]
```yaml

# traduction du modèle France en langue anglaise

transport . avion . usager:
  question: Do you fly ?

transport . avion . court courrier . heures de vol:
  suggestions:
    super low: 393003
    middle low: 8934940


transport . avion . long courrier . vitesse moyenne:
  note: |
   We estimate the speed instead of asking the user the kilometers, he can't answer that.


# i18n du modèle france en modèle écosse

# fonctionnalité : diff par rapport à modèle. Par exempl pour l'écosse, c'est bien plus pertinent de faire diverger le modèle UK que de faire diverger le modèle FR. 

transport . avion . long courrier . vitesse moyenne:
  formule: 6500 / 10
  note: |
    Because the ministry of aviation said so.

# i18n du modèle france en modèle polynésie

transport . avion:
  somme: 
    - vols internationaux
    - vols inter-île

transport . avion . vols internationaux: blabla

```

Algo : 

- je parse le modèle de référence -> objet JS
- je parse le modèle alternatif : si le chemin de clef existe déjà, je les écrase. Sinon je les ajoute
