### ISSUE TITLE
Règle et tag `Aide` : deux problèmes

### ISSUE THREAD

**Issue by simogeo** [datagir/nosgestesclimat#1868]
Dans la règle suivante `logement . électricité . consommation:` se trouve l'appel à l'aide `aide: estimation via le coût`

Dans le cadre d'une adaptation j'ai deux soucis avec cela et ne trouve pas mes réponses.

**1) Premier problème, le résultat est toujours multiplié par 12 !** 
Ce que je ne souhaite pas (car j'ai converti ma question sur l'électricité à une fréquence mensuelle). Changer les unités ne permet pas de stopper cette multiplication.

J'ai pensé utilisé le workaround de fournir une valeur divisée par 12 mais rien n'y fait, c'est toujours multiplié avant d'être affiché ? Ou puis-je changer cela ? Visiblement, ce n'est pas dans les fichiers yaml et je n'ai pas trouvé dans `nosgestesclimat-site`.

**2)  Second problème, en utilisant une variation dans la formule**

Celle-ci, ne semble pas fonctionner. Je me demande si "estimation via le coût" est bien la bonne valeur à tester ? Sinon quelle est-elle ? Et si c'est bien la bonne, pourquoi y  a t'il ce problème ?

```
logement . électricité . estimation via le coût:
  # formule: 0.1993 
  formule:
    variations:
      - si: estimation via le coût <= 6720
        alors: 2.333333333
     - sinon: 4
```

Merci de votre retour !!
