### ISSUE TITLE
Amélioration des valeurs par défaut - transport

### ISSUE THREAD

**Issue by JuliePouliquen** [datagir/nosgestesclimat#1884]
En lien avec #1437 

L'enquête mobilités de 2019 donne les valeurs moyennes du nombre de km annuels par type de véhicule et motorisation (pour les véhicules légers) : 
![km moyen par type véhicule](https://github.com/datagir/nosgestesclimat/assets/4005340/b8188c28-141b-4155-ba19-feb7df1b791e)

Je propose de passer la valeur par défaut pour les deux-roues thermiques à 3000 km.

Le tableau permet également d'affiner le chiffre pour la moyenne de km effectués en voiture... mais cela demande d'inverser le modèle et de demander d'abord la motorisation du véhicule : 

- Si essence : 8920
- Si diesel : 14392

(On peut arrondir à la centaine :smile:)

**Comment by Clemog** [comment]
Hyper intéressant pour les 2 roues ! 
Il me semble que le chiffre de 12200 est bien tiré de cette enquête, on pourrait faire la distinction au niveau de la valeur par défaut mis je ne sais pas si c'est vraiment intéressant ?

```yaml
par défaut:
    variations:
      - si: essence
        alors: 8900
      - si: diesel
        alors: 14400
      - sinon: 12200
```
